version: '2'

services:

  redmine:
    image: redmine:3.3.3-passenger
    restart: always
    environment:
      REDMINE_DB_POSTGRES: redmine-db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      HTTP_PROXY:
      HTTPS_PROXY:
      http_proxy:
      https_proxy:
      NO_PROXY: gitbucket
    ports:
      - "3000:3000"
    volumes_from:
      - redmine-data
    depends_on:
      - redmine-data
      - redmine-db

  redmine-data:
    image: busybox
    volumes:
      - /usr/src/redmine/files

  redmine-db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine
    volumes_from:
      - redmine-db-data
    depends_on:
      - redmine-db-data

  redmine-db-data:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
